#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: IPTables Firewall.
### END INIT INFO

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
start)
	log_daemon_msg "Starting Firewall..."
	/opt/scripts/firewall/firewall.sh
	log_end_msg 0
	exit 0
	;;
 
stop)
	log_daemon_msg "Stopping Firewall..."
	/opt/scripts/firewall/firewall.stop.sh
	log_end_msg 0
	exit 0
	;;
 
restart)
	log_daemon_msg "Stopping Firewall..."
	/opt/scripts/firewall/firewall.stop.sh
	log_end_msg 0
	log_daemon_msg "Starting Firewall..."
	/opt/scripts/firewall/firewall.sh
	log_end_msg 0
	exit 0
	;;
 
*)
	echo "Usage: /etc/init.d/firewall {start|stop|restart}"
	exit 1
	;;
esac
 
exit 0
